In [2]:
# GEOG 761 Project
# group 2

! python--version


/bin/bash: line 1: python--version: command not found


In [1]:
!pip install changeos

  Using cached changeos-0.2-py3-none-any.whl (3.2 kB)
  Using cached torch-2.0.1-cp310-cp310-manylinux1_x86_64.whl (619.9 MB)
  Using cached torchvision-0.15.2-cp310-cp310-manylinux1_x86_64.whl (6.0 MB)
  Using cached sympy-1.12-py3-none-any.whl (5.7 MB)
  Using cached nvidia_cuda_nvrtc_cu11-11.7.99-2-py3-none-manylinux1_x86_64.whl (21.0 MB)
  Using cached nvidia_cuda_runtime_cu11-11.7.99-py3-none-manylinux1_x86_64.whl (849 kB)
  Using cached nvidia_cuda_cupti_cu11-11.7.101-py3-none-manylinux1_x86_64.whl (11.8 MB)
  Using cached nvidia_cudnn_cu11-8.5.0.96-2-py3-none-manylinux1_x86_64.whl (557.1 MB)
  Using cached nvidia_cublas_cu11-11.10.3.66-py3-none-manylinux1_x86_64.whl (317.1 MB)
  Using cached nvidia_cufft_cu11-10.9.0.58-py3-none-manylinux1_x86_64.whl (168.4 MB)
  Using cached nvidia_curand_cu11-10.2.10.91-py3-none-manylinux1_x86_64.whl (54.6 MB)
  Using cached nvidia_cusolver_cu11-11.4.0.1-2-py3-none-manylinux1_x86_64.whl (102.6 MB)
  Using cached nvidia_cusparse_cu11-11.7.4.91-p

In [3]:
# changeos has four APIs
# (e.g., 'list_available_models', 'from_name', 'visualize', 'demo_data')
import changeos


# constructing ChangeOS model
# support 'changeos_r18', 'changeos_r34', 'changeos_r50', 'changeos_r101'
model = changeos.from_name('changeos_r101') # take 'changeos_r101' as example

# load your data or our prepared demo data
# numpy array of shape [1024, 1024, 3], [1024, 1024, 3]
pre_disaster_image, post_disaster_image = changeos.demo_data()

print(pre_disaster_image)

# model inference
loc, dam = model(pre_disaster_image, post_disaster_image)

# put color map on raw prediction
loc, dam = changeos.visualize(loc, dam)

# visualize by matplotlib
import matplotlib.pyplot as plt
plt.subplot(121)
plt.imshow(loc)
plt.subplot(122)
plt.imshow(dam)
plt.show()

[[[ 67  72  55]
  [ 64  70  53]
  [ 65  73  55]
  ...
  [ 44  57  39]
  [ 47  61  42]
  [ 46  60  42]]

 [[ 58  63  48]
  [ 64  69  53]
  [ 60  65  49]
  ...
  [ 52  67  45]
  [ 39  52  35]
  [ 45  61  41]]

 [[ 52  56  43]
  [ 50  54  41]
  [ 44  49  37]
  ...
  [ 68  86  58]
  [ 54  72  47]
  [ 53  72  47]]

 ...

 [[205 206 195]
  [195 199 187]
  [171 175 164]
  ...
  [ 91  91  69]
  [ 94  94  72]
  [101 101  78]]

 [[196 198 187]
  [189 191 180]
  [165 169 157]
  ...
  [ 91  91  69]
  [ 94  94  72]
  [101 101  78]]

 [[194 194 184]
  [191 191 180]
  [177 179 166]
  ...
  [ 96  95  74]
  [ 99  98  76]
  [ 99  99  76]]]


RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript, serialized code (most recent call last):
  File "code/__torch__/module/arch_encoder_decoder.py", line 15, in forward
    encoder = self.encoder
    _0, _1, _2, _3, _4, _5, _6, _7, = (encoder).forward(x, )
    _8 = (decoder).forward(_0, _1, _2, _3, _4, _5, _6, _7, )
          ~~~~~~~~~~~~~~~~ <--- HERE
    _9, _10, _11, = _8
    _12, _13, = (head).forward(_9, _10, _11, )
  File "code/__torch__/module/changeos_decoder.py", line 22, in forward
    loc_neck = self.loc_neck
    _0 = (loc_neck).forward(argument_1, argument_2, argument_3, argument_4, )
    _1 = (dam_neck).forward(argument_5, argument_6, argument_7, argument_8, )
          ~~~~~~~~~~~~~~~~~ <--- HERE
    input = torch.cat([_0, _1], 1)
    _2 = (_0, _0, (fuse_conv).forward(input, ))
  File "code/__torch__/torch/nn/modules/container/___torch_mangle_421.py", line 17, in forward
    _2 = (_0).forward(argument_1, argument_2, argument_3, argument_4, )
    _3, _4, _5, _6, = _2
    return (_1).forward(_3, _4, _5, _6, )
            ~~~~~~~~~~~ <--- HERE
  File "code/__torch__/ever/module/fpn/___torch_mangle_420.py", line 24, in forward
    _6 = (_2).forward(argument_3, )
    _7 = (_3).forward(argument_4, )
    _8 = torch.add(torch.add(_4, CONSTANTS.c2), _5)
                   ~~~~~~~~~ <--- HERE
    t2_features = torch.div(torch.add(torch.add(_8, _6), _7), CONSTANTS.c3)
    return t2_features

Traceback of TorchScript, original code (most recent call last):
/home/zz/anaconda3/envs/th110/lib/python3.9/site-packages/ever/module/fpn.py(182): forward
/home/zz/anaconda3/envs/th110/lib/python3.9/site-packages/torch/nn/modules/module.py(1090): _slow_forward
/home/zz/anaconda3/envs/th110/lib/python3.9/site-packages/torch/nn/modules/module.py(1102): _call_impl
/home/zz/anaconda3/envs/th110/lib/python3.9/site-packages/torch/nn/modules/container.py(141): forward
/home/zz/anaconda3/envs/th110/lib/python3.9/site-packages/torch/nn/modules/module.py(1090): _slow_forward
/home/zz/anaconda3/envs/th110/lib/python3.9/site-packages/torch/nn/modules/module.py(1102): _call_impl
/home/zz/wow21/reproduce_changeos/module/changeos_decoder.py(43): forward
/home/zz/anaconda3/envs/th110/lib/python3.9/site-packages/torch/nn/modules/module.py(1090): _slow_forward
/home/zz/anaconda3/envs/th110/lib/python3.9/site-packages/torch/nn/modules/module.py(1102): _call_impl
/home/zz/wow21/reproduce_changeos/module/arch_encoder_decoder.py(15): forward
/home/zz/anaconda3/envs/th110/lib/python3.9/site-packages/torch/nn/modules/module.py(1090): _slow_forward
/home/zz/anaconda3/envs/th110/lib/python3.9/site-packages/torch/nn/modules/module.py(1102): _call_impl
/home/zz/anaconda3/envs/th110/lib/python3.9/site-packages/torch/jit/_trace.py(958): trace_module
/home/zz/anaconda3/envs/th110/lib/python3.9/site-packages/torch/jit/_trace.py(741): trace
/home/zz/wow21/reproduce_changeos/jit_tool.py(11): <module>
RuntimeError: CUDA out of memory. Tried to allocate 64.00 MiB (GPU 0; 7.43 GiB total capacity; 6.61 GiB already allocated; 42.00 MiB free; 6.69 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
